#pragma once

enum DIRECTION { DIR_CENTER,DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END };

enum OBJID { OBJ_PLAYER, OBJ_MONSTER, OBJ_BULLET, OBJ_WATERSPOT, OBJ_MULJULGY, OBJ_BLOCK, OBJ_TILE,OBJ_ITEM, OBJ_PET, OBJ_2048, OBJ_ZELDA, OBJ_BUTTON, OBJ_BOSS, OBJ_END };

enum SCENEID { SC_LOGO, SC_STAGE, SC_STAGE2 ,SC_EDIT, SC_WAITING, SC_SHOP, SC_MINIGAME,SC_END };

enum BLOCKTYPE { BLOCK_CAN_BREAK, BLOCK_CANNOT_BREAK, BLOCK_FLAG };

enum RENDERID { RENDER_BACKGROUND, RENDER_GAMEOBJECT, RENDER_EFFECT, RENDER_UI, RENDER_END };

enum ITEMTYPE { ITEM_WATERBOMB, ITEM_NEEDLE, ITEM_ROLLER, ITEM_MEDICINE, ITEM_MONEY_GOLD, ITEM_MONEY_SILVER, ITEM_MONEY_COPPER, ITEM_SHOES,ITEM_SHIELD,ITEM_END };

enum STATE { IDLE, RIGHT_LEFT, UP_DOWN, WHILEBUBBLE, BREAKBUBBLE, PANGBUBBLE, WIN, BOSS_HIT ,BOSS_DEAD, END };

enum CHANNELID { SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MONSTER, SOUND_UI, MAXCHANNEL };